### ISSUE TITLE
PL generation categories

### ISSUE THREAD

**Issue by jihwanp** [xiaofeng94/VL-PLM#3]
Hi thanks for providing such a nice work!
I have a question about the categories that you've used for PL generation.
It seems that you used only novel COCO categories for PL in unlabeld images.
Does the other datasets (.e.g, LVIS, Object365) also use only novel categories for PL generation?

And one more thing I'm curious about is that as mentioned in table1, VL-PLM used web-crawled image-text pair, but I can't find what it uses.

Thanks

**Comment by xiaofeng94** [comment]
Hey, other category names from other datasets are not used in major COCO experiments. But your may find some results with other category names in the supplement ([arXiv version](https://arxiv.org/abs/2207.08954)), like `B.3 Modeling Background in PL Generation` and `Table 11`.

We used CLIP to generate pseudo labels. CLIP requires web-crawled image-text pairs for training, so we claim image-text pairs were used in our method

**Comment by jihwanp** [comment]
Thanks for your comment :) 
BTW, are you planning to update the code for the semi-supervised experiment later?
It would be great if you provide it since there have been no such work using CLIP in semi sup. learning. 
Thanks!

**Comment by xiaofeng94** [comment]
Hey, we adopted an offline PL method STAC for semi-supervised learning. You can generate PLs (in COCO format) with our code and use them in [STAC code](https://github.com/google-research/ssl_detection). There will be no or few things to be modified, e.g. dataloader.
