### ISSUE TITLE
About the class agnostic proposal generator

### ISSUE THREAD

**Issue by Feobi1999** [xiaofeng94/VL-PLM#6]
I see the classes=1 in the config file of your proposal generator. I want to know how you train this model? Did you regard the 48 categories as one classes and train a standard Faster-RCNN detector？ Thanks

**Comment by xiaofeng94** [comment]
Hey,

That's what we did. We take 48 categories as one category `Object`. So all bounding boxes belong to this category during training and `num_classes=1`.
