### ISSUE TITLE
Where is the pre-training model import path changed when using the following command for evaluation?

### ISSUE THREAD

**Issue by luoyq6** [xiaofeng94/VL-PLM#8]
![image](https://user-images.githubusercontent.com/110521846/224246245-7227fb65-939a-4de5-9995-603e3dddc974.png)

**Comment by xiaofeng94** [comment]
Hey, you may try `python -m train_net.py --config configs/coco_openvoc_LSJ.yaml  --num-gpus=1 --eval-only MODEL.WEIGHTS <path-to-model-weights>`.

**Comment by luoyq6** [comment]
OK，thank
